# Generated by Django 4.2 on 2024-04-27 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0002_alter_datousuario_usuario"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Datousuario",
            new_name="Datosusuario",
        ),
    ]
