# Generated by Django 4.2 on 2024-04-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_rename_datousuario_datosusuario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datosusuario",
            options={
                "ordering": ["usuario"],
                "verbose_name": "Datos del usuario",
                "verbose_name_plural": "Datos de los usuarios",
            },
        ),
    ]
