# Generated by Django 4.2 on 2024-04-12 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Oferta", "Oferta"),
                            ("Publicado", "Publicado"),
                            ("Vendido", "Vendido"),
                            ("En Falta", "En Falta"),
                        ],
                        default="Publicado",
                        max_length=10,
                    ),
                ),
                ("producto", models.CharField(max_length=200)),
                (
                    "fecha_publicacion",
                    models.DateTimeField(verbose_name="Fecha de publicación"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="producto/%Y/%m/%d"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        default="Descripción no disponible", max_length=500
                    ),
                ),
                ("precio", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.categoria",
                    ),
                ),
            ],
        ),
    ]
